//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Thesis.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_GMLTYPE                     129
#define IDR_GRAPH                       134
#define IDC_EDGE_CURSOR                 136
#define IDC_VERTEX_CURSOR               137
#define IDC_REMOVE_CURSOR               138
#define IDD_NEW_VERTEX_DIALOG           139
#define IDD_NEW_GRAPH_DIALOG            140
#define IDD_NEW_EDGE_DIALOG             141
#define IDB_EMAIL_BITMAP                143
#define IDB_NEXT_BITMAP                 144
#define IDB_PREV_BITMAP                 145
#define IDD_OPTIONS_DIALOG              146
#define IDD_VERTEX_TAB                  147
#define IDD_EDGE_TAB                    149
#define IDD_VERTEX_PROPERTIES_DIALOG    152
#define IDD_EDGE_PROPERTIES_DIALOG      153
#define IDD_ANIMATION_DIALOG            154
#define IDR_UTILITIES                   157
#define IDD_OUTPUT_DIALOG               159
#define IDR_ALGORITHMS                  162
#define IDR_ANIMATION                   164
#define IDD_RESIZE_GRAPH_DIALOG         165
#define IDR_EDIT                        166
#define IDR_NETWORK                     171
#define IDD_GENERATE_GRAPH_DIALOG       175
#define IDD_GRAPH_PROPERTIES_DIALOG     177
#define IDB_SKY                         178
#define IDD_DELAY_TIME_DIALOG           179
#define IDD_SEARCH_DIALOG               180
#define IDC_EDIT                        1000
#define IDC_SPIN                        1001
#define IDC_DIRECTED_RADIO              1002
#define IDC_UNDIRECTED_RADIO            1003
#define IDC_LISTS_RADIO                 1004
#define IDC_MATRIX_RADIO                1005
#define IDC_EMAIL_BUTTON                1006
#define IDC_TAB                         1007
#define IDC_PREV_BUTTON                 1009
#define IDC_NEXT_BUTTON                 1010
#define IDC_CHECK                       1011
#define IDC_COMBO                       1013
#define IDC_NUMBER_EDIT                 1015
#define IDC_TYPE_EDIT                   1016
#define IDC_WEIGHT_EDIT                 1017
#define IDC_CHANGE_COLOR_BUTTON         1018
#define IDC_NETWORK_EDGE_CHECK          1019
#define IDC_NAME_EDIT                   1020
#define IDC_CAPACITY_EDIT               1021
#define IDC_COLOR                       1022
#define IDC_FAST_INSERT_CHECK           1035
#define IDC_APPLY_BUTTON                1038
#define ID_APPLY_BUTTON                 1039
#define IDC_MODEL                       1044
#define IDC_CURRENT_EDIT                1047
#define IDC_NEW_EDIT                    1048
#define IDC_NUMV_EDIT                   1050
#define IDC_VERTEX_COMBO                1051
#define IDC_EDGE_COMBO                  1052
#define IDC_VWU_EDIT                    1053
#define IDC_NUME_EDIT                   1054
#define IDC_EWU_EDIT                    1055
#define IDC_ECU_EDIT                    1056
#define IDC_VERTEX_SPIN                 1057
#define IDC_EDGE_SPIN                   1058
#define IDC_STRUCTURE                   1060
#define IDC_VERTEX_NUM                  1061
#define IDC_EDGE_NUM                    1062
#define IDC_MAX_SIZE                    1063
#define IDC_TYPE                        1064
#define IDC_VERTEX_TYPE                 1065
#define IDC_EDGE_TYPE                   1066
#define IDC_LABEL1                      1067
#define IDC_LABEL2                      1068
#define IDC_LABEL3                      1069
#define IDC_OLD                         1070
#define IDC_START_EDIT                  1072
#define IDC_GOAL_EDIT                   1073
#define IDC_START_SPIN                  1074
#define IDC_GOAL_SPIN                   1075
#define ID_GRAPH_SELECT                 32771
#define ID_GRAPH_VERTEX                 32772
#define ID_GRAPH_EDGE                   32773
#define ID_GRAPH_REMOVE                 32774
#define ID_GRAPH_PROPERTIES             32775
#define ID_TOOLS_OPTIONS                32776
#define ID_EDIT_DELETE                  32778
#define ID_UTILITIES_BFT                32782
#define ID_UTILITIES_TOPO               32783
#define ID_ALGORITHM_PRIM               32784
#define ID_ALGORITHM_KRUSKAL            32785
#define ID_ALGORITHM_DIJKSTRA           32786
#define ID_ALGORITHM_FLOYD              32787
#define ID_UTILITIES_EULER              32788
#define ID_UTILITIES_CUT_VERTEX         32789
#define ID_OPTIONS_AUTOMATIC            32791
#define ID_OPTIONS_MANUAL               32792
#define ID_ANIMATION_NEXT               32793
#define ID_ANIMATION_RESET              32794
#define ID_UTILITIES_COLOR              32795
#define ID_ALGORITHM_BELLMAN_FORD       32796
#define ID_UTILITIES_BRIDGE_EDGE        32797
#define ID_UTILITIES_CONNECTED_COMPONENTS 32798
#define ID_UTILITIES_BICONNECTED_COMPONENTS 32799
#define ID_UTILITIES_CONNECTED_COMPONENT 32800
#define ID_UTILITIES_BICONNECTED_COMPONENT 32801
#define ID_UTILITIES_TRANSITIVE_CLOSURE 32802
#define ID_UTILITIES_CYCLE              32803
#define ID_GRAPH_GENERATE_COMPLETEGRAPH 32804
#define ID_GRAPH_GENERATE_RANDOMGRAPH   32805
#define ID_ALGORITHM_CRITICAL_PATH      32806
#define ID_ALGORITHM_SSP_DAG            32807
#define ID_NETWORK_CHECK                32808
#define ID_NPC_PLANAR                   32809
#define ID_NPC_HAMILTON                 32810
#define ID_VIEW_GRAPH                   32811
#define ID_VIEW_ALGORITHMS              32812
#define ID_VIEW_UTILITIES               32813
#define ID_VIEW_OUTPUT                  32815
#define ID_VIEW_NETWORK                 32816
#define ID_NETWORK_FORD_FULKERSON       32817
#define ID_NETWORK_RESIDUAL             32818
#define ID_UTILITIES_VERTEX_COVER       32819
#define ID_GRAPH_RESIZE                 32820
#define ID_GRAPH_CLEAR                  32821
#define ID_LAYOUT_ELLIPSE               32823
#define ID_OPTIONS_DELAYTIME            32824
#define ID_DEMO_FORDFULKERSON           32825
#define ID_DEMO_FORD_FULKERSON          32826
#define ID_NETWORK_MAXIMUM_BIPARTITE_MATCHING 32827
#define ID_ALGORITHM_JOHNSON            32828
#define ID_UTILITIES_PREORDER           32829
#define ID_UTILITIES_POSTORDER          32830
#define ID_UTILITIES_HAMILTON           32831
#define ID_ALGORITHM_ASTAR              32832
#define ID_ALGORITHM_TSP                32833
#define ID_ALGORITHM_CHINESE_POSTMAN    32834
#define ID_DEMO_ASTAR                   32835

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         32836
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
